import type { Metadata } from "next";
import "./globals.css";
import { OutfitFontFamily } from "./assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OutfitFontFamily.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
